### ISSUE TITLE
`this == nullptr` results in undefined behavior

### ISSUE THREAD

**Issue by ShortDevelopment** [chakra-core/ChakraCore#6978]
## Issue
‘this’ pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true

## Tasks
- [ ] Add compiler warning 
clang: [`-Wundefined-bool-conversion`](https://clang.llvm.org/docs/DiagnosticsReference.html#id939)
msvc: ??
- [x] #6847
- [ ] [`IR.cpp`](https://github.com/chakra-core/ChakraCore/blob/2af598f04ab508f9231d6e26f0f82f5a57561413/lib/Backend/IR.cpp#L4852)
- [x] Find further places where this may happen

**Comment by ppenzin** [comment]
This warning should now be enabled in Clang by default, though didn't catch this earlier due to `-Werror`, I suspect it wasn't enabled in the version from the package manager.

**Comment by ShortDevelopment** [comment]
https://github.com/chakra-core/ChakraCore/blob/2af598f04ab508f9231d6e26f0f82f5a57561413/lib/Backend/IR.cpp#L4852

**Comment by rhuanjl** [comment]
I had a look IR.cpp and the invalid check is being done part of a Debug only feature; so it's not as critical a concern as ImmutableList.

I've also done a sequence of searches in the codebase and I don't think there's anything else.
